# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Learn"
license = "MIT"
# licenselink = "https://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"
description = "Python programming class"
homepage = "https://github.com/matcornic/hugo-theme-learn/"
repo = "https://github.com/matcornic/hugo-theme-learn"
tags = ["documentation", "grav", "learn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Alim"
  # homepage = "https://matcornic.github.io/"

[original]
  name = "Alim"
  # homepage = "https://learn.getgrav.org/"
  # repo = "https://github.com/getgrav/grav-learn"
